version: "3.5"
services:
   db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/procedures.sql:/docker-entrypoint-initdb.d/procedures.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"