version: "3.8"
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
      - DATABASE_HOST=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./sql/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./sql/1_functions.sql:/docker-entrypoint-initdb.d/1_functions.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
  api1:
    image: luizvnasc/rinha_backend_2024_q1
    hostname: api1
    environment:
      - PORT=3000
      - POSTGRES_DSN=host=db user=admin password=123 dbname=rinha port=5432 sslmode=disable TimeZone=Europe/Lisbon
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
  api2:
    image: luizvnasc/rinha_backend_2024_q1
    hostname: api2
    environment:
      - PORT=3001
      - POSTGRES_DSN=host=db user=admin password=123 dbname=rinha port=5432 sslmode=disable TimeZone=Europe/Lisbon
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
  load-balancer:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 9999:9999
    depends_on:
      - api1
      - api2

networks:
  default:
    driver: bridge
    name: rinha-backend-2024q1