
@baseURL = localhost:9999
@clientID = 1

###
POST {{baseURL}}/clientes/{{clientID}}/transacoes
Content-Type: application/json

{
    "valor": 100,
    "tipo": "d",
    "descricao":"teste"
}


###
GET {{baseURL}}/clientes/{{clientID}}/extrato


###

GET localhost:9999
